---
- name: gerrit_replication | configuring gerrit replication
  template:
    src: "replication.config.j2"
    dest: "{{ gerrit_site_dir }}/etc/replication.config"
    owner: "{{ gerrit_account_info.name }}"
    group: "{{ gerrit_account_info.group }}"
    mode: 0644
  notify: restart gerrit
