---
# tasks file for ansible-gerrit
- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: configure_gitweb.yml

- include: install_gerrit.yml
